// <auto-generated />
namespace PharmAssistant.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DiscountType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DiscountType));
        
        string IMigrationMetadata.Id
        {
            get { return "201903191519446_DiscountType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
